"""Pi / Oh-My-Pi adapter for luau-check.

Mechanism (verified against can1357/oh-my-pi source, docs/extensions.md):
- oh-my-pi (and its upstream Pi by mariozechner) load TS/JS extension modules
  auto-discovered from `<cwd>/.omp/extensions` (project) or
  `~/.omp/agent/extensions` (user, default agent dir).
- An extension is a module with a default factory that receives the
  ExtensionAPI: `pi.on("tool_result", handler)` fires after every tool
  execution (middleware-style). Handler can read event.toolName / event.input
  and can return `{ continue: true, additionalContext }`.
- We filter write/edit tools with a file path, run luau-check, and return
  diagnostics as additionalContext when errors exist (advisory).

Install strategy:
  1. Write `~/.omp/agent/extensions/luau-check.ts` (user scope).
  2. Extension shells out to the absolute luau-check CLI.
  3. Idempotent; uninstall removes the file.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from ..version import __version__


def agent_extensions_dir() -> Path:
    """User-level agent extensions dir (~/.omp/agent/extensions or PI env)."""
    base = os.environ.get("PI_CODING_AGENT_DIR")
    if base:
        return Path(base) / "extensions"
    return Path.home() / ".omp" / "agent" / "extensions"


def extension_path() -> Path:
    return agent_extensions_dir() / "luau-check.ts"


def _luau_check_command() -> str:
    found = shutil.which("luau-check")
    if found and os.path.isabs(found):
        return found
    import sys
    return f"{sys.executable} -m luau_check.cli"


def extension_ts_content(luau_check_cmd: str) -> str:
    cmd_json = __import__("json").dumps(luau_check_cmd)
    return f'''// luau-check oh-my-pi / pi extension (v{__version__})
// Generated by luau-check install-agent.
// Runs luau-check on edited Luau files after tool execution.
import {{ execFileSync }} from "node:child_process"

const LUAU_CHECK = {cmd_json}

// The command may be "<python> -m luau_check.cli" (two tokens) when the CLI
// is not on PATH, or a single binary path on a normal install. Split it so
// execFileSync always receives a real executable name + argv (no shell).
const LUAU_CHECK_PARTS = LUAU_CHECK.split(" ")
const LUAU_CHECK_BIN = LUAU_CHECK_PARTS[0]
const LUAU_CHECK_ARGS = LUAU_CHECK_PARTS.slice(1)

export default function (pi: any) {{
  pi.setLabel?.("luau-check")

  pi.on("tool_result", async (event: any) => {{
    const toolName: string = event?.toolName ?? event?.tool ?? ""
    // omp tool names are lowercase ("write", "edit", ...); match case-insensitively
    if (!/write|edit|create|patch|apply/i.test(toolName)) return

    const input = event?.input ?? event?.toolInput ?? {{}}
    const fp: string | undefined =
      input?.file_path ?? input?.filePath ?? input?.path ?? input?.file
    if (!fp || !(fp.endsWith(".luau") || fp.endsWith(".lua"))) return

    try {{
      execFileSync(LUAU_CHECK_BIN, [...LUAU_CHECK_ARGS, "check", "--json", fp], {{
        encoding: "utf-8",
        timeout: 30000,
        stdio: ["ignore", "pipe", "ignore"],
      }})
    }} catch (e: any) {{
      const stderr = e?.stdout?.toString?.() ?? e?.stderr?.toString?.() ?? ""
      if (stderr.trim()) {{
        // omp tool_result handlers patch the result content (ToolResultEventResult);
        // there is no additionalContext channel on tool_result.
        const existing = Array.isArray(event?.content) ? event.content : []
        return {{
          content: [
            ...existing,
            {{ type: "text", text: `[luau-check] ${{stderr.trim().replace(/\\n/g, " | ")}}` }},
          ],
        }}
      }}
    }}
  }})
}}
'''


def install_extension(luau_check_cmd: str | None = None) -> Path:
    luau_check_cmd = luau_check_cmd or _luau_check_command()
    path = extension_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(extension_ts_content(luau_check_cmd), encoding="utf-8")
    return path


def is_installed() -> bool:
    return extension_path().exists()


def uninstall_extension() -> bool:
    if not extension_path().exists():
        return False
    extension_path().unlink()
    return True
