"""Pi / Oh-My-Pi adapter for luau-check.

Mechanism (verified against can1357/oh-my-pi source, docs/extensions.md):
- oh-my-pi (and its upstream Pi by mariozechner) load TS/JS extension modules
  auto-discovered from `<cwd>/.omp/extensions` (project) or
  `~/.omp/agent/extensions` (user, default agent dir).
- An extension is a module with a default factory that receives the
  ExtensionAPI: `pi.on("tool_result", handler)` fires after every tool
  execution (middleware-style). Handler can read event.toolName / event.input
  and can return `{ continue: true, additionalContext }`.
- We filter write/edit tools with a file path, run luau-check, and return
  diagnostics as additionalContext when errors exist (advisory).

Install strategy:
  1. Write `~/.omp/agent/extensions/luau-check.ts` (user scope).
  2. Extension shells out to the absolute luau-check CLI.
  3. Idempotent; uninstall removes the file.
"""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path

from ..version import __version__


def agent_extensions_dir() -> Path:
    """User-level agent extensions dir (~/.omp/agent/extensions or PI env)."""
    base = os.environ.get("PI_CODING_AGENT_DIR")
    if base:
        return Path(base) / "extensions"
    return Path.home() / ".omp" / "agent" / "extensions"


def extension_path() -> Path:
    return agent_extensions_dir() / "luau-check.ts"


def _luau_check_command() -> str:
    found = shutil.which("luau-check")
    if found and os.path.isabs(found):
        return found
    import sys
    return f"{sys.executable} -m luau_check.cli"


def extension_ts_content(luau_check_cmd: str) -> str:
    cmd_json = __import__("json").dumps(luau_check_cmd)
    return f'''// luau-check oh-my-pi / pi extension (v{__version__})
// Generated by luau-check install-agent.
// Runs luau-check on edited Luau files after tool execution.
import {{ execFileSync }} from "node:child_process"

const LUAU_CHECK = {cmd_json}

// The command may be "<python> -m luau_check.cli" (two tokens) when the CLI
// is not on PATH, or a single binary path on a normal install. Split on the
// " -m " separator ONLY so a python path containing a space (Program Files)
// survives as one token.
const LUAU_CHECK_PARTS = LUAU_CHECK.split(" -m ")
const LUAU_CHECK_BIN = LUAU_CHECK_PARTS[0]
const LUAU_CHECK_ARGS = LUAU_CHECK_PARTS.length > 1 ? ["-m", LUAU_CHECK_PARTS[1]] : []

export default function (pi: any) {{
  pi.setLabel?.("luau-check")

  pi.on("tool_result", async (event: any) => {{
    const toolName: string = event?.toolName ?? event?.tool ?? ""
    // omp tool names are lowercase ("write", "edit", ...); match case-insensitively
    if (!/write|edit|create|patch|apply/i.test(toolName)) return

    const input = event?.input ?? event?.toolInput ?? {{}}
    const fp: string | undefined =
      input?.file_path ?? input?.filePath ?? input?.path ?? input?.file
    if (!fp || !(fp.endsWith(".luau") || fp.endsWith(".lua"))) return

    try {{
      execFileSync(LUAU_CHECK_BIN, [...LUAU_CHECK_ARGS, "check", "--json", fp], {{
        encoding: "utf-8",
        timeout: 30000,
        stdio: ["ignore", "pipe", "ignore"],
      }})
    }} catch (e: any) {{
      const stderr = e?.stdout?.toString?.() ?? e?.stderr?.toString?.() ?? ""
      if (stderr.trim()) {{
        // omp tool_result handlers patch the result content (ToolResultEventResult);
        // there is no additionalContext channel on tool_result.
        const existing = Array.isArray(event?.content) ? event.content : []
        return {{
          content: [
            ...existing,
            {{ type: "text", text: `[luau-check] ${{stderr.trim().replace(/\\n/g, " | ")}}` }},
          ],
        }}
      }}
    }}
  }})
}}
'''


def agent_settings_path() -> Path:
    """~/.omp/agent/settings.json (or PI_CODING_AGENT_DIR equivalent)."""
    base = os.environ.get("PI_CODING_AGENT_DIR")
    if base:
        return Path(base) / "settings.json"
    return Path.home() / ".omp" / "agent" / "settings.json"


def register_in_settings(ext_path: Path) -> None:
    """Modern pi/omp loads extensions from settings.json `extensions` array.

    Older pi auto-scanned `~/.omp/agent/extensions/`; omp >= 17 requires the
    extension module path to be explicitly configured (or passed via
    `--extension`). Write the absolute path into settings so discovery is
    deterministic on every pi/omp version.
    """
    p = agent_settings_path()
    data = {}
    if p.exists():
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            data = {}
    if not isinstance(data, dict):
        data = {}
    exts = data.get("extensions")
    if not isinstance(exts, list):
        exts = []
    target = str(ext_path)
    if target not in exts:
        exts.append(target)
    data["extensions"] = exts
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def unregister_in_settings(ext_path: Path) -> bool:
    p = agent_settings_path()
    if not p.exists():
        return False
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return False
    exts = data.get("extensions")
    if not isinstance(exts, list):
        return False
    target = str(ext_path)
    if target not in exts:
        return False
    exts.remove(target)
    data["extensions"] = exts
    p.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return True


def install_extension(luau_check_cmd: str | None = None) -> Path:
    luau_check_cmd = luau_check_cmd or _luau_check_command()
    path = extension_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(extension_ts_content(luau_check_cmd), encoding="utf-8")
    register_in_settings(path)
    return path


def is_installed() -> bool:
    return extension_path().exists()


def uninstall_extension() -> bool:
    removed = False
    if extension_path().exists():
        extension_path().unlink()
        removed = True
    if unregister_in_settings(extension_path()):
        removed = True
    return removed
