"""OpenCode adapter for luau-check.

Mechanism (verified against sst/opencode source, packages/plugin):
- OpenCode loads plugins from `~/.config/opencode/plugin/` (user) or
  `<proj>/.opencode/plugin/` (project). A plugin module exports a `Plugin`
  factory returning `Hooks` with an `event(input: { event: Event })` hook.
- The `event` hook receives SDK Event objects including tool calls/results.
  We filter for tool events that carry a file path (Edit/Write-style) and run
  luau-check on the file, logging diagnostics as feedback.
- The plugin API is IDENTICAL on opencode v1 (1.x, current stable) and v2
  (2.0 branch) — verified by diffing `packages/plugin/src/index.ts` on both.
  One plugin module covers both versions.
- Plugins are loaded per-version through the same `plugin` config key; we
  write TS and rely on opencode's own module loading.

Install strategy:
  1. Write `~/.config/opencode/plugin/luau-check.ts` (user scope, all projects).
  2. Plugin code shells out to the absolute luau-check CLI path.
  3. Idempotent: overwrite own file; uninstall removes it.

Note: this adapter generates a TS file. The luau-check CLI does the heavy
lifting; the plugin is a thin event -> subprocess bridge.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from ..version import __version__

# opencode user config dir (XDG or default)
def opencode_home() -> Path:
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg) / "opencode" if xdg else Path.home() / ".config" / "opencode"
    return base


def plugin_dir() -> Path:
    # opencode looks for plugins in <config>/plugin with package.json,
    # and also supports single-file TS modules in <config>/plugin/module.ts
    return opencode_home() / "plugin"


def plugin_file_path() -> Path:
    return plugin_dir() / "luau-check.ts"


def _luau_check_command() -> str:
    found = shutil.which("luau-check")
    if found and os.path.isabs(found):
        return found
    import sys
    return f"{sys.executable} -m luau_check.cli"


def plugin_ts_content(luau_check_cmd: str) -> str:
    """Generated opencode plugin module.

    Uses the `event` hook (available on opencode v1 + v2). Detects tool
    events that carry a file path and shells out to luau-check.
    """
    # Need to escape the cmd into a JS string safely
    cmd_json = __import__("json").dumps(luau_check_cmd)
    return f'''// luau-check opencode plugin (v{__version__})
// Generated by luau-check install-agent. Covers opencode v1 and v2
// (identical plugin API). Runs luau-check on edited Luau files.
import {{ execFileSync }} from "node:child_process"

const LUAU_CHECK = {cmd_json}

// The command may be "<python> -m luau_check.cli" (two tokens) when the CLI
// is not on PATH, or a single binary path on a normal install. Split on the
// " -m " separator ONLY so a python path containing a space (Program Files)
// survives as one token.
const LUAU_CHECK_PARTS = LUAU_CHECK.split(" -m ")
const LUAU_CHECK_BIN = LUAU_CHECK_PARTS[0]
const LUAU_CHECK_ARGS = LUAU_CHECK_PARTS.length > 1 ? ["-m", LUAU_CHECK_PARTS[1]] : []

// Determine if an opencode Event looks like a file-editing tool result.
// opencode Event model (from @opencode-ai/sdk): file edits surface as
// `message.part.updated` events whose part is a tool part with its
// state.toolInput carrying file_path once the call completes.
function extractFilePath(event: any): string | null {{
  if (!event || typeof event !== "object") return null

  // message.part.updated -> properties.part
  const part = event?.properties?.part ?? event?.part
  if (!part || part.type !== "tool") return null

  const name = String(part?.tool ?? part?.toolName ?? "")
  if (!/Edit|Write|MultiEdit|Create|Patch/i.test(name)) return null

  // ToolState.toolInput may be a string (JSON) or object
  const state = part?.state ?? part?.toolState ?? {{}}
  let input = state?.toolInput ?? state?.input ?? state ?? {{}}
  if (typeof input === "string") {{
    try {{ input = JSON.parse(input) }} catch {{ return null }}
  }}

  const fp = input?.file_path ?? input?.filePath ?? input?.path ?? input?.file
  if (typeof fp === "string" && (fp.endsWith(".luau") || fp.endsWith(".lua"))) {{
    return fp
  }}
  return null
}}

export async function luauCheck(event: any): Promise<void> {{
  const fp = extractFilePath(event)
  if (!fp) return
  try {{
    execFileSync(LUAU_CHECK_BIN, [...LUAU_CHECK_ARGS, "check", "--json", fp], {{
      encoding: "utf-8",
      timeout: 30000,
      stdio: ["ignore", "pipe", "ignore"],
    }})
    // If clean, execFileSync returns; we only surface errors (non-zero exit)
  }} catch (e: any) {{
    // Non-zero exit => diagnostics. Surface them.
    const stderr = e?.stdout?.toString?.() ?? e?.stderr?.toString?.() ?? ""
    if (stderr.trim()) {{
      console.log(`[luau-check] ${{stderr.trim().replace(/\\n/g, " | ")}}`)
    }}
  }}
}}

const plugin = {{
  id: "luau-check",
  server: async (input: any, _options?: any) => {{
    return {{
      event: async ({{ event }}: any) => {{
        await luauCheck(event)
      }},
    }}
  }},
}}

export default plugin
'''


def install_plugin(luau_check_cmd: str | None = None) -> Path:
    """Write the opencode plugin module. Returns its path. Idempotent."""
    luau_check_cmd = luau_check_cmd or _luau_check_command()
    path = plugin_file_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(plugin_ts_content(luau_check_cmd), encoding="utf-8")
    return path


def is_installed() -> bool:
    return plugin_file_path().exists()


def uninstall_plugin() -> bool:
    if not plugin_file_path().exists():
        return False
    plugin_file_path().unlink()
    return True
